# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: https://youlianboshi.netlify.app/
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/clash
- type: subscribe
  options:
    url: https://www.liesauer.net/yogurt/subscribe?ACCESS_TOKEN=DAYxR3mMaZAsaqUb
- type: subscribe
  options:
    url: https://qiaomenzhuanfx.netlify.app/
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzz
  options:
    url: https://view.freev2ray.org/
- type: webfuzz
  options:
    url: https://fanqiang.network/free-v2ray
- type: webfuzz
  options:
    url: https://fanqiang.network/shadowsocks-servers
 - type: webfuzz
  options:
    url: https://viencoding.com/ss-ssr-share  
# tg频道    
# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: SSRSUB
    num: 200
- type: tgchannel
  options:
    channel: ShadowsocksRssr
    num: 200
- type: tgchannel
  options:
    channel: ssList
    num: 200
- type: tgchannel
  options:
    channel: V2List
    num: 200
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 200
- type: tgchannel
  options:
    channel: socks5list
    num: 200
- type: tgchannel
  options:
    channel: ssrshares
    num: 200
- type: tgchannel
  options:
    channel: onessr
    num: 200
- type: tgchannel
  options:
    channel: baipiaojiedian
    num: 200
- type: tgchannel
  options:
    channel: ShareCentre
    num: 200
# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-36-1.html
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-2-1.html
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-50-1.html
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-51-1.html
# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
- type: clash
  options:
    url: https://proxypoolss.tk/clash/proxies

# 某个网站抓取
- type: web-freessrxyz
  options:
  url: https://lncn.org/
